FROM node:20-alpine

WORKDIR /app

# Install dependencies and OpenSSL for Prisma
COPY package*.json ./
RUN apk add --no-cache openssl docker-cli
RUN npm install

# We don't copy the source code here because we will map it as a volume in docker-compose.yml
# This allows hot-reloading to work!

# Expose port
EXPOSE 5000

# Start command
CMD ["npm", "run", "dev"]
