FROM node:20-alpine

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

# We don't copy the source code here because we will map it as a volume in docker-compose.yml
# This allows hot-reloading to work!

# Expose port
EXPOSE 5173

# Start command
CMD ["npm", "run", "dev", "--", "--host"]
